version: '3.8'

services:
  
  # api:
  #   container_name: api-container
  #   image: node:16
  #   working_dir: /usr/src/api
  #   restart: always
  #   command: bash -c "npm install --only=prod && npm start"
  #   volumes:
  #       - ./dist/:/usr/src/api/dist/
  #       - ./package.json:/usr/src/api/package.json
  #   ports:
  #       - 3333:3333
  #   networks:
  #     - api-network

  postgres:
    container_name: postgres-container
    image: postgres:14
    restart: always
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
    volumes:
        - db-data:/var/lib/postgresql/data
    ports:
        - 5432:5432
    networks:
      - api-network

  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: jeordane.batista@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "5433:80"
    depends_on:
      - postgres
    networks:
      - api-network

networks: 

  api-network:
    driver: bridge

volumes:
  db-data: 
    driver: local